AWS_S3:
  READ_BUCKET: vsingh-spark-test-data
  DROP_LOCATION: droplocation
  WRITE_BUCKET: vsingh-spark-apps-write-data
  WRITE_LOCATION: stream-write

KAFKA_CONF:
  SERVER: ec2-34-243-68-20.eu-west-1.compute.amazonaws.com
  PORT: 9092
  TOPIC: testmq
  KAFKA_CHECKPOINT_LOCATION: kafka-checkpoint-location
